trigger:
- main

pool: 'WDKubePool'


steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i ''s/\r$//'' ''./configure-ingress-controller.sh'''
    workingDirectory: "testportal/"
- task: Bash@3
  inputs:
    filePath: 'testportal/configure-ingress-controller.sh'
    arguments: 'walletdoc2 ingress.yml'
    workingDirectory: "testportal/"
