trigger:
- main

pool: 'WDKubePool'


steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Current directory: $(pwd)"  # Print working directory
      npm install @azure/msal-node

      
- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'wddev-k8s service connection'
    namespace: 'default'
    command: login
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i ''s/\r$//'' ''./configure-ingress-controller.sh'''
    workingDirectory: "testportal/"
- task: Bash@3
  inputs:
    filePath: 'testportal/configure-ingress-controller.sh'
    arguments: 'walletdoc4 ingress.yml'
    workingDirectory: "testportal/"
