trigger:
- main

pool: 'WDKubePool'


steps:

- task: NodeTool@0
  inputs:
    versionSpec: 'v22.3.0'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Current directory: $(pwd)"  # Print working directory
      echo "Node.js version: $(node -v)"  # Print Node.js version (if installed)
      npm install @azure/msal-node@2.10.1
      
- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'wddev-k8s service connection'
    namespace: 'default'
    command: login

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i ''s/\r$//'' ''./configure-ingress-controller.sh'''
    workingDirectory: "testportal/"
- task: Bash@3
  inputs:
    filePath: 'testportal/configure-ingress-controller.sh'
    arguments: 'walletdoc4 ingress.yml'
    workingDirectory: "testportal/"
