apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: walletdoc-portal
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: star-walletdoc-tech
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
spec:
  rules:
    - host: portal.walletdoc.tech
      http:
        paths:
          - path: /*
            backend:
              service:
                name: walletdoc-portal
                port:
                  number: 80
            pathType: Prefix

