apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: walletdoc-portal
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: star-walletdoc-tech
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
spec:
  rules:
    - host: portal.walletdoc.tech
      http:
        paths:
          - path: /walletdocportal
            backend:
              service:
                name: walletdoc-portal
                port:
                  number: 80
            pathType: Prefix
          - path: /testportal
            backend:
              service:
                name: test-portal
                port:
                  number: 80
            pathType: Prefix  


---

apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: walletdoc-portal
spec:
  selector:
    app: walletdoc-portal
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer

---

apiVersion : apps/v1
kind: Deployment
metadata:
  name: walletdoc-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walletdoc-portal
  template:
    metadata:
      labels:
        app: walletdoc-portal
    spec:
      containers:
        - name: walletdoc-portal
          image: wddevcontainerregistry.azurecr.io/walletdoc-portal:latest
          ports:
            - containerPort: 80
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: test-portal
spec:
  selector:
    app: test-portal
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer


---


apiVersion : apps/v1
kind: Deployment
metadata:
  name: test-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-portal
  template:
    metadata:
      labels:
        app: test-portal
    spec:
      containers:
        - name: walletdoc-portal
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
