---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: walletdoc-portal
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: star-walletdoc-tech
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
spec:
  rules:
  - host: portal.walletdoc.tech
    http:
      paths:
      - path: /
        backend:
          service:
            name: walletdoc-portal
            port:
              number: 80
        pathType: Prefix
  - host: testportal.walletdoc.tech  # Separate hostname for /testportal
    http:
      paths:
      - path: /
        backend:
          service:
            name: nginx-service
            port:
              number: 80
        pathType: Prefix 


---

apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: walletdoc-portal
spec:
  selector:
    app: walletdoc-portal
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer

---

apiVersion : apps/v1
kind: Deployment
metadata:
  name: walletdoc-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walletdoc-portal
  template:
    metadata:
      labels:
        app: walletdoc-portal
    spec:
      containers:
        - name: walletdoc-portal
          image: wddevcontainerregistry.azurecr.io/walletdoc-portal:latest
          ports:
            - containerPort: 80
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
